services:
  - docker

stages:
  - name: build docker image
    if: (branch != master && tag IS blank) || type != push
  - name: deploy docker image
    if: (branch = master || tag IS present) && type = push

jobs:
  include:
    - stage: build docker image
      script: docker build -t $DOCKER_IMAGE_NAME .

    - stage: deploy docker image
      script:
        - |
          if [ ! -z "$TRAVIS_TAG" ]; then
            export IMAGE_TAG=$TRAVIS_TAG
          else
            export IMAGE_TAG='latest'
          fi
        - docker build -t $DOCKER_IMAGE_NAME:$IMAGE_TAG .
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push $DOCKER_IMAGE_NAME:$IMAGE_TAG
